export const DATA = [
    {
        dates: { maximum: "2023-02-18", minimum: "2023-01-01" },
        page: 1,
        results: [
            {
                adult: false,
                backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
                genre_ids: [28, 12, 878],
                id: 505642,
                original_language: "en",
                original_title: "Black Panther: Wakanda Forever",
                overview:
                    "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
                popularity: 5334.97,
                poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
                release_date: "2022-11-09",
                title: "Black Panther: Wakanda Forever",
                video: false,
                vote_average: 7.5,
                vote_count: 3298,
            },
            {
                adult: false,
                backdrop_path: "/b1Y8SUb12gPHCSSSNlbX4nB3IKy.jpg",
                genre_ids: [16, 12, 35, 10751, 14],
                id: 315162,
                original_language: "en",
                original_title: "Puss in Boots: The Last Wish",
                overview:
                    "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
                popularity: 3911.777,
                poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
                release_date: "2022-12-07",
                title: "Puss in Boots: The Last Wish",
                video: false,
                vote_average: 8.5,
                vote_count: 3840,
            },
            {
                adult: false,
                backdrop_path: "/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
                genre_ids: [28, 12, 53],
                id: 646389,
                original_language: "en",
                original_title: "Plane",
                overview:
                    "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
                popularity: 3841.265,
                poster_path: "/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg",
                release_date: "2023-01-13",
                title: "Plane",
                video: false,
                vote_average: 6.8,
                vote_count: 490,
            },
            {
                adult: false,
                backdrop_path: "/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
                genre_ids: [28, 10749, 35],
                id: 758009,
                original_language: "en",
                original_title: "Shotgun Wedding",
                overview:
                    "Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.",
                popularity: 2357.698,
                poster_path: "/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg",
                release_date: "2022-12-28",
                title: "Shotgun Wedding",
                video: false,
                vote_average: 6.4,
                vote_count: 480,
            },
            {
                adult: false,
                backdrop_path: "/3JSoB7eMbCd8sE8alxNiUtrNiTz.jpg",
                genre_ids: [12, 878, 35],
                id: 640146,
                original_language: "en",
                original_title: "Ant-Man and the Wasp: Quantumania",
                overview:
                    "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
                popularity: 2068.712,
                poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
                release_date: "2023-02-10",
                title: "Ant-Man and the Wasp: Quantumania",
                video: false,
                vote_average: 6.6,
                vote_count: 431,
            },
            {
                adult: false,
                backdrop_path: "/q2fY4kMXKoGv4CQf310MCxpXlRI.jpg",
                genre_ids: [878, 27, 35],
                id: 536554,
                original_language: "en",
                original_title: "M3GAN",
                overview:
                    "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
                popularity: 2088.921,
                poster_path: "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
                release_date: "2022-12-28",
                title: "M3GAN",
                video: false,
                vote_average: 7.5,
                vote_count: 1661,
            },
            {
                adult: false,
                backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
                genre_ids: [878, 12, 28],
                id: 76600,
                original_language: "en",
                original_title: "Avatar: The Way of Water",
                overview:
                    "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
                popularity: 1738.087,
                poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
                release_date: "2022-12-14",
                title: "Avatar: The Way of Water",
                video: false,
                vote_average: 7.7,
                vote_count: 5342,
            },
            {
                adult: false,
                backdrop_path: "/a4I481szRmycyreQTLrRe4f4YJe.jpg",
                genre_ids: [80, 53, 18],
                id: 842544,
                original_language: "en",
                original_title: "Transfusion",
                overview:
                    "Ryan Logan, a former Special Forces operative, is battling to cope with life after the loss of his wife.  He is thrusted into the criminal underworld to keep his only son from being taken from him.",
                popularity: 1409.278,
                poster_path: "/bxh5xCCW9Ynfg6EZJWUkc1zqTnr.jpg",
                release_date: "2023-01-05",
                title: "Transfusion",
                video: false,
                vote_average: 6.7,
                vote_count: 94,
            },
            {
                adult: false,
                backdrop_path: "/tCpMRsHlfR6CcqJYA3kJMS3YApt.jpg",
                genre_ids: [28, 80, 53],
                id: 1035806,
                original_language: "en",
                original_title: "Detective Knight: Independence",
                overview:
                    "Detective James Knight 's last-minute assignment to the Independence Day shift turns into a race to stop an unbalanced ambulance EMT from imperiling the city's festivities. The misguided vigilante, playing cop with a stolen gun and uniform, has a bank vault full of reasons to put on his own fireworks show... one that will strike dangerously close to Knight's home.",
                popularity: 1164.669,
                poster_path: "/jrPKVQGjc3YZXm07OYMriIB47HM.jpg",
                release_date: "2023-01-20",
                title: "Detective Knight: Independence",
                video: false,
                vote_average: 6.3,
                vote_count: 61,
            },
            {
                adult: false,
                backdrop_path: "/cU7itLM8qmwMiaNnWsJPQLKe79j.jpg",
                genre_ids: [878, 27, 12, 28],
                id: 1013870,
                original_language: "en",
                original_title: "Kids vs. Aliens",
                overview:
                    "All Gary wants is to make awesome home movies with his best buds. All his older sister Samantha wants is to hang with the cool kids. When their parents head out of town one Halloween weekend, an all-time rager of a teen house party turns to terror when aliens attack, forcing the siblings to band together to survive the night.",
                popularity: 974.881,
                poster_path: "/wQ53sO5n9LCFbssV3oQ4CuajL1L.jpg",
                release_date: "2023-01-20",
                title: "Kids vs. Aliens",
                video: false,
                vote_average: 6.2,
                vote_count: 30,
            },
            {
                adult: false,
                backdrop_path: "/pketzKFjq5TERXoXFM3L0OYRCLe.jpg",
                genre_ids: [16, 10751],
                id: 599019,
                original_language: "ru",
                original_title: "Большое путешествие. Специальная доставка",
                overview:
                    "It has been a year since Mic Mic and Oscar returned from their incredible adventure. And now, after a diabolical plan by Vulture to sabotage the delivery of the Grizzly cub to his opponent in the American presidential elections, Mic Mic, Oscar, Panda teenager and Stork set off on another great adventure as they ride a zeppelin to return little Grizzly to its rightful parents and save the American elections and the whole continent from an erupting volcano.",
                popularity: 901.398,
                poster_path: "/dabXVfrAFfhDte8XVemom3mTJog.jpg",
                release_date: "2022-10-07",
                title: "Big Trip 2: Special Delivery",
                video: false,
                vote_average: 6.5,
                vote_count: 11,
            },
            {
                adult: false,
                backdrop_path: "/5pMy5LF2JAleBNBtuzizfCMWM7k.jpg",
                genre_ids: [10752, 36, 18],
                id: 653851,
                original_language: "en",
                original_title: "Devotion",
                overview:
                    "The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy's most celebrated wingmen.",
                popularity: 935.014,
                poster_path: "/26yQPXymbWeCLKwcmyL8dRjAzth.jpg",
                release_date: "2022-11-23",
                title: "Devotion",
                video: false,
                vote_average: 7.5,
                vote_count: 309,
            },
            {
                adult: false,
                backdrop_path: "/Aqldsq65Nj1KAkQD2MzkZsAk5N5.jpg",
                genre_ids: [28, 53, 18],
                id: 846433,
                original_language: "es",
                original_title: "The Enforcer",
                overview:
                    "A noir thriller set in Miami, the film follows an enforcer who discovers his femme fatale boss has branched out into cyber sex trafficking, putting a young runaway he’s befriended at risk. He sacrifices everything to save the young girl from the deadly organization he’s spent his life building.",
                popularity: 916.981,
                poster_path: "/pXC8JJbfnRWtbD8i2yKFqqWEO4X.jpg",
                release_date: "2022-09-22",
                title: "The Enforcer",
                video: false,
                vote_average: 7.3,
                vote_count: 221,
            },
            {
                adult: false,
                backdrop_path: "/kc4Tuc0aONtPOqOs0PAPQGmJren.jpg",
                genre_ids: [18],
                id: 785084,
                original_language: "en",
                original_title: "The Whale",
                overview:
                    "A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.",
                popularity: 790.44,
                poster_path: "/pjnxR9Yw83Vi7Dsl49K3rJcKWk4.jpg",
                release_date: "2022-12-09",
                title: "The Whale",
                video: false,
                vote_average: 7.6,
                vote_count: 137,
            },
            {
                adult: false,
                backdrop_path: "/pV9cKtUOpJFTG9Ub816XhTpQMbF.jpg",
                genre_ids: [53, 27],
                id: 746524,
                original_language: "en",
                original_title: "Blood",
                overview:
                    "Jess, a newly separated mother and nurse, moves into her old family farmhouse with Tyler, her teenage daughter, and Owen, her eight-year-old son. One night, the family dog senses something in the woods and runs off to find it. He returns a couple of days later and attacks Owen, savagely biting him before Jess is able to intervene. Owen is rushed to the hospital. His condition worsens, and no one can figure out why... until Jess discovers a disturbing cure...",
                popularity: 782.291,
                poster_path: "/gCUFtTvjK4gbmjVxhx8bhyOhAeW.jpg",
                release_date: "2023-01-12",
                title: "Blood",
                video: false,
                vote_average: 6.2,
                vote_count: 29,
            },
            {
                adult: false,
                backdrop_path: "/f9PSbuMeBS5CuHEOVyymg5lcq8J.jpg",
                genre_ids: [28, 53, 9648, 80, 27],
                id: 996727,
                original_language: "en",
                original_title: "The Price We Pay",
                overview:
                    "After a pawn shop robbery goes askew, two criminals take refuge at a remote farmhouse to try to let the heat die down, but find something much more menacing.",
                popularity: 832.018,
                poster_path: "/8fwJt0qZieQ7dKaiiqehObWpXYT.jpg",
                release_date: "2023-01-13",
                title: "The Price We Pay",
                video: false,
                vote_average: 6.2,
                vote_count: 62,
            },
            {
                adult: false,
                backdrop_path: "/8oj1pbizI6RS5xlyETmlWh9mVqN.jpg",
                genre_ids: [27],
                id: 955991,
                original_language: "en",
                original_title: "The Offering",
                overview:
                    "In the wake of a young Jewish girl’s disappearance, the son of a Hasidic funeral director returns home with his pregnant wife in hopes of reconciling with his father. Little do they know that directly beneath them in the family morgue, an ancient evil with sinister plans for the unborn child lurks inside a mysterious corpse.",
                popularity: 760.602,
                poster_path: "/tbaTFgGIaTL1Uhd0SMob6Dhi5cK.jpg",
                release_date: "2023-01-11",
                title: "The Offering",
                video: false,
                vote_average: 5.8,
                vote_count: 84,
            },
            {
                adult: false,
                backdrop_path: "/vXjpwkXPirBmgdEpIknfN8ziDD.jpg",
                genre_ids: [16, 12, 14, 35],
                id: 947938,
                original_language: "ru",
                original_title: "Мальчик-дельфин",
                overview:
                    "When a plane crashes at sea, dolphins rescue a little boy and raise him as family. He lives a carefree life beneath the waves until an evil monster seizes power over the underwater world. The boy is banished to dry land, where a kind-hearted captain takes him in. With the captain’s help, the boy sets out on a journey to solve the mystery of his true identity.",
                popularity: 700.991,
                poster_path: "/gISoDEiaUH9BNEunmLC7FgUVaia.jpg",
                release_date: "2022-04-07",
                title: "Dolphin Boy",
                video: false,
                vote_average: 5.9,
                vote_count: 27,
            },
            {
                adult: false,
                backdrop_path: "/xTsERrOCW15OIYl5aPX7Jbj38wu.jpg",
                genre_ids: [28, 18, 36],
                id: 724495,
                original_language: "en",
                original_title: "The Woman King",
                overview:
                    "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
                popularity: 639.383,
                poster_path: "/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
                release_date: "2022-09-16",
                title: "The Woman King",
                video: false,
                vote_average: 7.8,
                vote_count: 1256,
            },
            {
                adult: false,
                backdrop_path: "/gwRMwljwHoNCyyJVgMA2XC4qPUU.jpg",
                genre_ids: [18, 35],
                id: 615777,
                original_language: "en",
                original_title: "Babylon",
                overview:
                    "A tale of outsized ambition and outrageous excess, tracing the rise and fall of multiple characters in an era of unbridled decadence and depravity during Hollywood's transition from silent films and to sound films in the late 1920s.",
                popularity: 566.281,
                poster_path: "/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg",
                release_date: "2022-12-22",
                title: "Babylon",
                video: false,
                vote_average: 7.6,
                vote_count: 1082,
            },
        ],
        total_pages: 70,
        total_results: 1398,
    },
]
